services:
  spinmatch:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - ${INGEST_HOST_DIR:-./ingest}:/data/ingest
      - ${MUSIC_HOST_DIR:-./music}:/data/music
